export interface MenuItem {
  id: number;
  name: string;
  category: "kebab" | "burger" | "kroznik" | "pizza" | "falafel";
  categoryLabel: string;
  price: number;
  student: boolean;
  vegi: boolean;
  image: string;
  icon: string;
  desc: string;
  note?: string;
  ingredientsList: string[];
  allergensList: string[];
}

export interface MenuCategoryMeta {
  id: string;
  label: string;
  shortLabel?: string;
  icon: string;
  image: string;
}

export const MENU_CATEGORIES: MenuCategoryMeta[] = [
  { id: "all", label: "Vse Jedi", shortLabel: "Vse", icon: "✨", image: "/images/hero-platter.jpg" },
  { id: "kebab", label: "Kebab & Jufke", shortLabel: "Kebab", icon: "🌯", image: "/images/doner-kebab.jpg" },
  { id: "burger", label: "Burgeri", shortLabel: "Burgeri", icon: "🍔", image: "/images/burger.jpg" },
  { id: "kroznik", label: "Krožniki & Piščanec", shortLabel: "Krožniki", icon: "🍗", image: "/images/chicken-platter.jpg" },
  { id: "pizza", label: "Pizze", shortLabel: "Pizze", icon: "🍕", image: "/images/pizza.jpg" },
  { id: "falafel", label: "Falafel & Priloge", shortLabel: "Falafel", icon: "🧆", image: "/images/falafel.jpg" },
];

export const MENU_ITEMS: MenuItem[] = [
  // 1. Kebab & Jufke
  {
    id: 1,
    name: "Doner Kebab",
    category: "kebab",
    categoryLabel: "Kebab & Jufke",
    price: 6.0,
    student: true,
    vegi: false,
    image: "/images/doner-kebab.jpg",
    icon: "🥪",
    desc: "Sveže pečeno meso, domača lepinja po hišnem receptu, mešana solata in izbrane omake.",
    ingredientsList: [
      "Domača sveže pečena lepinja",
      "Telečje & piščančje döner meso (100% Halal)",
      "Hrustljava solata, paradižnik, zelje, čebula",
      "Hišna kremasta jogurtova omaka",
    ],
    allergensList: ["Gluten (pšenica)", "Laktoza (mleko)", "Sezam"],
  },
  {
    id: 2,
    name: "Jufka Kebab",
    category: "kebab",
    categoryLabel: "Kebab & Jufke",
    price: 7.0,
    student: true,
    vegi: false,
    image: "/images/durum-falafel.jpg",
    icon: "🌯",
    desc: "Meso po izbiri zavito v tanko testo s svežo zelenjavo in domačimi omakami.",
    ingredientsList: [
      "Tanek domači lavaš / tortilja",
      "Sočno döner meso pečeno na ognju",
      "Sveža mešana zelenjava",
      "Izbrani prelivi (blagi ali pekoči)",
    ],
    allergensList: ["Gluten (pšenica)", "Laktoza (mleko)"],
  },
  {
    id: 3,
    name: "Kebab Krožnik",
    category: "kebab",
    categoryLabel: "Kebab & Jufke",
    price: 9.0,
    student: false,
    vegi: false,
    image: "/images/hero-platter.jpg",
    icon: "🍽️",
    desc: "Bogat krožnik kebab mesa, hrustljav pomfri, sveža mešana solata ter hišni prelivi.",
    ingredientsList: [
      "Velika porcija kebab mesa",
      "Zlato ocvrt pomfri",
      "Bogata solatna priloga",
      "Hišna omaka & lepinja kruhek",
    ],
    allergensList: ["Gluten (pšenica)", "Laktoza (mleko)", "Sezam"],
  },
  {
    id: 4,
    name: "Kebab v Škatli",
    category: "kebab",
    categoryLabel: "Kebab & Jufke",
    price: 7.0,
    student: false,
    vegi: false,
    image: "/images/doner-kebab.jpg",
    icon: "🥡",
    desc: "Praktična porcija sočnega kebab mesa s hrustljavim pomfrijem in izbranimi omakami.",
    ingredientsList: [
      "Rezine mariniranega mesa",
      "Hrustljav krompirček pomfri",
      "Solata in omake po želji",
    ],
    allergensList: ["Gluten (pšenica)", "Laktoza (mleko)"],
  },
  {
    id: 5,
    name: "Zelenjavni Kebab",
    category: "kebab",
    categoryLabel: "Kebab & Jufke",
    price: 4.0,
    student: true,
    vegi: true,
    image: "/images/falafel.jpg",
    icon: "🥗",
    desc: "Bogat izbor sveže zelenjave, sira in posebnih aromatičnih zeliščnih prelivov v topli lepinji.",
    ingredientsList: [
      "Domača topla lepinja",
      "Feta sir / riban sir",
      "Paradižnik, kumare, zelje, koruza, čebula",
      "Zeliščni jogurtov preliv",
    ],
    allergensList: ["Gluten (pšenica)", "Laktoza (mleko)"],
  },
  {
    id: 6,
    name: "Zelenjavna Jufka",
    category: "kebab",
    categoryLabel: "Kebab & Jufke",
    price: 4.5,
    student: true,
    vegi: true,
    image: "/images/durum-falafel.jpg",
    icon: "🌯",
    desc: "Sveža sezonska zelenjava in izbrane omake, zavite v toplo tanko tortiljo.",
    ingredientsList: [
      "Tanek lavaš zvitek",
      "Raznolika hrustljava solata",
      "Kremasti sir & prelivi",
    ],
    allergensList: ["Gluten (pšenica)", "Laktoza (mleko)"],
  },

  // 2. Falafel & Priloge
  {
    id: 7,
    name: "Falafel Sendvič",
    category: "falafel",
    categoryLabel: "Falafel & Priloge",
    price: 7.0,
    student: true,
    vegi: true,
    image: "/images/falafel.jpg",
    icon: "🧆",
    desc: "Hrustljavi čičerikini polpeti po pristnem orientalskem receptu v topli lepinji s solato in tahinijem.",
    ingredientsList: [
      "Domači hrustljavi falafli",
      "Sveža lepinja",
      "Tahini sezamova omaka",
      "Paradižnik, kisle kumarice, peteršilj",
    ],
    allergensList: ["Gluten (pšenica)", "Sezam"],
  },
  {
    id: 8,
    name: "Falafel XL",
    category: "falafel",
    categoryLabel: "Falafel & Priloge",
    price: 8.0,
    student: false,
    vegi: true,
    image: "/images/falafel.jpg",
    icon: "🧆",
    desc: "Večja porcija hrustljavih falaflov z dodatno svežo zelenjavo in kremastim humusom.",
    ingredientsList: [
      "Ekstra porcija falafel kroglic",
      "Humus namaz & tahini",
      "Bogat izbor solate",
    ],
    allergensList: ["Gluten (pšenica)", "Sezam"],
  },
  {
    id: 9,
    name: "Falafel Krožnik",
    category: "falafel",
    categoryLabel: "Falafel & Priloge",
    price: 8.9,
    student: false,
    vegi: true,
    image: "/images/falafel.jpg",
    icon: "🍽️",
    desc: "Falafel kroglice, zlati pomfri, sveža mešana solata, pita kruhek in orientalske omake.",
    ingredientsList: [
      "6x zlati falafel polpeti",
      "Pomfri krompirček",
      "Sveža solata & pita kruh",
      "Tahini & česnova omaka",
    ],
    allergensList: ["Gluten (pšenica)", "Sezam"],
  },
  {
    id: 10,
    name: "Falafel + Humus",
    category: "falafel",
    categoryLabel: "Falafel & Priloge",
    price: 10.0,
    student: false,
    vegi: true,
    image: "/images/falafel.jpg",
    icon: "🧆",
    desc: "Kombinacija hrustljavih falaflov in domačega kremastega humusa z oljčnim oljem.",
    ingredientsList: [
      "Sveži falafli",
      "Domač kremni čičerikin humus",
      "Deviško oljčno olje & pita",
    ],
    allergensList: ["Gluten (pšenica)", "Sezam"],
  },
  {
    id: 11,
    name: "Falafel (kos)",
    category: "falafel",
    categoryLabel: "Falafel & Priloge",
    price: 1.0,
    student: false,
    vegi: true,
    image: "/images/falafel.jpg",
    icon: "🧆",
    desc: "Posamezen hrustljav ocvrt falafel po pristnem tradicionalnem receptu.",
    ingredientsList: ["Čičerika, česen, peteršilj, orientalske začimbe"],
    allergensList: ["Sezam"],
  },
  {
    id: 12,
    name: "Humus porcija",
    category: "falafel",
    categoryLabel: "Falafel & Priloge",
    price: 3.0,
    student: false,
    vegi: true,
    image: "/images/falafel.jpg",
    icon: "🥣",
    desc: "Kremast tradicionalni namaz iz čičerike z deviškim oljčnim oljem in začimbami.",
    ingredientsList: ["Čičerika, tahini, limonin sok, česen, oljčno olje"],
    allergensList: ["Sezam"],
  },
  {
    id: 13,
    name: "Pomfri",
    category: "falafel",
    categoryLabel: "Falafel & Priloge",
    price: 3.0,
    student: false,
    vegi: true,
    image: "/images/chicken-platter.jpg",
    icon: "🍟",
    desc: "Zlato ocvrt, hrustljav in soljen krompirček, pripravljen sproti ob naročilu.",
    ingredientsList: ["Krompir, rastlinsko olje, morska sol"],
    allergensList: [],
  },
  {
    id: 14,
    name: "Dnevna Juha",
    category: "falafel",
    categoryLabel: "Falafel & Priloge",
    price: 3.0,
    student: false,
    vegi: true,
    image: "/images/student-meal.jpg",
    icon: "🍲",
    desc: "Vsak dan sveže skuhana domača topla juha z izbrano zelenjavo in zelišči.",
    ingredientsList: ["Sveža zelenjava, začimbe, domača jušna osnova"],
    allergensList: ["Zelena"],
  },

  // 3. Krožniki & Piščanec
  {
    id: 15,
    name: "Piščančji Svet (z rižem)",
    category: "kroznik",
    categoryLabel: "Krožniki & Piščanec",
    price: 8.9,
    student: true,
    vegi: false,
    image: "/images/chicken-platter.jpg",
    icon: "🍚",
    desc: "Sočni kosi mariniranega piščanca z aromatičnim rumenim rižem in svežo solato.",
    ingredientsList: [
      "Marinirani piščančji file (100% Halal)",
      "Aromatičen riž z začimbami",
      "Sveža solatna priloga",
      "Hišna jogurtova omaka",
    ],
    allergensList: ["Laktoza (mleko)"],
  },
  {
    id: 16,
    name: "Piščančji Svet (s pomfrijem)",
    category: "kroznik",
    categoryLabel: "Krožniki & Piščanec",
    price: 8.9,
    student: true,
    vegi: false,
    image: "/images/chicken-platter.jpg",
    icon: "🍟",
    desc: "Hrustljavo pečen piščanec v kombinaciji z zlatim pomfrijem in hišnimi prelivi.",
    ingredientsList: [
      "Sočni piščančji kosi",
      "Hrustljav krompirček pomfri",
      "Mešana sezonska solata",
      "Izbrana pomaka",
    ],
    allergensList: ["Laktoza (mleko)"],
  },
  {
    id: 17,
    name: "Crispy Jufka",
    category: "kroznik",
    categoryLabel: "Krožniki & Piščanec",
    price: 7.0,
    student: true,
    vegi: false,
    image: "/images/durum-falafel.jpg",
    icon: "🌯",
    desc: "Hrustljavo paniran piščančji zrezek, sveža solata in blaga majonezna omaka v tortilji.",
    ingredientsList: [
      "Paniran hrustljav piščančji file",
      "Pšenična tortilja",
      "Solata, paradižnik, blaga omaka",
    ],
    allergensList: ["Gluten (pšenica)", "Jajca", "Laktoza (mleko)"],
  },
  {
    id: 18,
    name: "Crispy Krožnik",
    category: "kroznik",
    categoryLabel: "Krožniki & Piščanec",
    price: 8.9,
    student: false,
    vegi: false,
    image: "/images/chicken-platter.jpg",
    icon: "🍗",
    desc: "Panirani hrustljavi piščančji medaljoni s pomfrijem, solato in hišno pomako.",
    ingredientsList: [
      "Hrustljavo ocvrti piščančji zrezki",
      "Zlati pomfri",
      "Sveža solata & hišna omaka",
    ],
    allergensList: ["Gluten (pšenica)", "Jajca", "Laktoza (mleko)"],
  },
  {
    id: 19,
    name: "Pečeni Piščanec",
    category: "kroznik",
    categoryLabel: "Krožniki & Piščanec",
    price: 7.9,
    student: true,
    vegi: false,
    image: "/images/chicken-platter.jpg",
    icon: "🍗",
    desc: "Sveže pečen sočen piščanec z izbranimi začimbami in domačimi prilogami.",
    ingredientsList: [
      "Pečen piščančji file",
      "Priloga po izbiri (riž ali pomfri)",
      "Solata z zeliščnim prelivom",
    ],
    allergensList: ["Laktoza (mleko)"],
  },
  {
    id: 20,
    name: "Čevapčiči",
    category: "kroznik",
    categoryLabel: "Krožniki & Piščanec",
    price: 11.0,
    student: false,
    vegi: false,
    image: "/images/hero-platter.jpg",
    icon: "🥙",
    desc: "100% goveji čevapčiči po tradicionalnem receptu v topli lepinji s čebulo in kajmakom.",
    ingredientsList: [
      "100% goveji čevapčiči (Halal)",
      "Domača topla lepinja",
      "Sveža narezana čebula",
      "Kremast domači kajmak & ajvar",
    ],
    allergensList: ["Gluten (pšenica)", "Laktoza (mleko)"],
  },

  // 4. Burgeri
  {
    id: 21,
    name: "Crispy Burger",
    category: "burger",
    categoryLabel: "Burgeri",
    price: 6.5,
    student: true,
    vegi: false,
    image: "/images/burger.jpg",
    icon: "🍔",
    desc: "Hrustljav paniran piščančji file, sveža solata, paradižnik in hišna burger omaka v mehkem kruhku.",
    ingredientsList: [
      "Sezamov burger kruhek",
      "Paniran hrustljav piščanec",
      "Solata, paradižnik, kisle kumarice",
      "Kremasta burger omaka",
    ],
    allergensList: ["Gluten (pšenica)", "Jajca", "Sezam", "Laktoza (mleko)"],
  },
  {
    id: 22,
    name: "Piščančji Burger",
    category: "burger",
    categoryLabel: "Burgeri",
    price: 6.5,
    student: true,
    vegi: false,
    image: "/images/burger.jpg",
    icon: "🍔",
    desc: "Nežen na žaru pečen piščančji file z osvežilnimi dodatki v mehkem sezamovem kruhku.",
    ingredientsList: [
      "Grill piščančji file",
      "Burger kruhek s sezamom",
      "Paradižnik, solata, hišni preliv",
    ],
    allergensList: ["Gluten (pšenica)", "Sezam", "Laktoza (mleko)"],
  },
  {
    id: 23,
    name: "Hamburger",
    category: "burger",
    categoryLabel: "Burgeri",
    price: 7.0,
    student: true,
    vegi: false,
    image: "/images/burger.jpg",
    icon: "🍔",
    desc: "Klasična sočna goveja polpeta, kumarice, rdeča čebula, sveža solata in hišna BBQ omaka.",
    ingredientsList: [
      "100% goveja polpeta (Halal)",
      "Mehka popečena bombetka",
      "Paradižnik, kumarice, čebula",
      "Klasična burger pomaka",
    ],
    allergensList: ["Gluten (pšenica)", "Sezam", "Gorčica"],
  },
  {
    id: 24,
    name: "Hamburger s Sirom",
    category: "burger",
    categoryLabel: "Burgeri",
    price: 7.5,
    student: true,
    vegi: false,
    image: "/images/burger.jpg",
    icon: "🍔",
    desc: "Klasičen burger z izdatno rezino stopljenega sira cheddar, sočnim govejim mesom in omako.",
    ingredientsList: [
      "Sočna goveja polpeta",
      "Topljen cheddar sir",
      "Hrustljava solata & kumarice",
      "Hišna omaka",
    ],
    allergensList: ["Gluten (pšenica)", "Laktoza (mleko)", "Sezam", "Gorčica"],
  },

  // 5. Pizze
  {
    id: 25,
    name: "Pizza Margarita",
    category: "pizza",
    categoryLabel: "Pizze",
    price: 8.0,
    student: true,
    vegi: true,
    image: "/images/pizza.jpg",
    icon: "🍕",
    note: "Opcija L: 9,50 €",
    desc: "Domača paradižnikova omaka, kakovostna mocarela, oljčno olje in dišeč origano.",
    ingredientsList: [
      "Domače ročno vlečeno testo",
      "Paradižnikovi pelati",
      "Mocarela sir",
      "Origano & oljčno olje",
    ],
    allergensList: ["Gluten (pšenica)", "Laktoza (mleko)"],
  },
  {
    id: 26,
    name: "Pizza Klasik",
    category: "pizza",
    categoryLabel: "Pizze",
    price: 8.0,
    student: true,
    vegi: false,
    image: "/images/pizza.jpg",
    icon: "🍕",
    note: "Opcija L: 9,50 €",
    desc: "Paradižnikovi pelati, mocarela sir, puranja šunka (Halal) in sveži šampinjoni.",
    ingredientsList: [
      "Testo iz krušne peči",
      "Pelati & mocarela",
      "Kakovostna šunka",
      "Sveži šampinjoni",
    ],
    allergensList: ["Gluten (pšenica)", "Laktoza (mleko)"],
  },
  {
    id: 27,
    name: "Pizza Salami",
    category: "pizza",
    categoryLabel: "Pizze",
    price: 8.0,
    student: true,
    vegi: false,
    image: "/images/pizza.jpg",
    icon: "🍕",
    note: "Opcija L: 9,50 €",
    desc: "Pelati, mocarela sir in pikantna goveja salama z začimbami.",
    ingredientsList: [
      "Hrustljavo testo",
      "Paradižnikova osnova & sir",
      "Goveja salama / kulen",
    ],
    allergensList: ["Gluten (pšenica)", "Laktoza (mleko)"],
  },
  {
    id: 28,
    name: "Pizza Kebab",
    category: "pizza",
    categoryLabel: "Pizze",
    price: 8.0,
    student: true,
    vegi: false,
    image: "/images/pizza.jpg",
    icon: "🍕",
    note: "Opcija L: 9,50 €",
    desc: "Pelati, sir, bogata porcija sočnega kebab mesa in izbrana hišna bela jogurtova omaka.",
    ingredientsList: [
      "Hrustljavo testo",
      "Mocarela & paradižnik",
      "Kebab meso pečeno na ognju",
      "Hišni beli preliv",
    ],
    allergensList: ["Gluten (pšenica)", "Laktoza (mleko)"],
  },
  {
    id: 29,
    name: "Pizza Tuna",
    category: "pizza",
    categoryLabel: "Pizze",
    price: 8.0,
    student: true,
    vegi: false,
    image: "/images/pizza.jpg",
    icon: "🍕",
    note: "Opcija L: 9,50 €",
    desc: "Paradižnikovi pelati, mocarela sir, izbrani koščki tune, rdeča čebula in olive.",
    ingredientsList: [
      "Domače testo",
      "Pelati & mocarela",
      "Kakovostna tuna",
      "Čebula & mediteranska zelišča",
    ],
    allergensList: ["Gluten (pšenica)", "Laktoza (mleko)", "Ribe"],
  },
  {
    id: 30,
    name: "Pizza Zelenjava",
    category: "pizza",
    categoryLabel: "Pizze",
    price: 8.0,
    student: true,
    vegi: true,
    image: "/images/pizza.jpg",
    icon: "🍕",
    note: "Opcija L: 9,50 €",
    desc: "Pelati, sir, sveža paprika, sladka koruza, šampinjoni, paradižnik in olive.",
    ingredientsList: [
      "Testo iz krušne peči",
      "Mocarela sir & pelati",
      "Paprika, gobe, paradižnik, koruza",
      "Origano",
    ],
    allergensList: ["Gluten (pšenica)", "Laktoza (mleko)"],
  },
];
